apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-secret-check-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-secret-check
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-secret-check
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-secret-check
subjects:
- kind: ServiceAccount
  name: k8s-secret-check-sa
