name: Docker Build and Push

on:
  workflow_dispatch: {}
  push:
    #branches: [ "master" ]
    branches: [ "*" ]  # XXX
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          # This would be confusing because the real one runs in the docker
          # image
          disable_annotations: true

      - name: Build Image
        run: make docker

      - name: Log into registry ${{ env.REGISTRY }}
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: make push
